export default  [
    {
        id: 1,
        token: "834jabfaifakdnfad2874rjahdfkafki234wykafkadfadaf",
        title: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid ab blanditiis alias expedita omnis, illo.",
        handle: "This-is-the-title",
        info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore deserunt ullam sapiente a impedit mollitia obcaecati at eligendi id facilis iure nesciunt minus, dolores doloribus deleniti ipsum! Nobis fugiat omnis facere ullam, vero magnam ipsa quos debitis natus provident assumenda cum eligendi. A, totam eaque doloremque molestias officia non eveniet.",
        img: "blog_img1.jpg",
        authorId: "sudkumar",
        authorName: "Sudhir Mitharwal",
        publishedDate: "2016-06-01",
        content: "Lorem ipsum dolor sit bold __amet__, consectetur adipisicing italic _elit_. Qui deleniti [link_name](http://www.domain.com \"Title of link\") recusandae, quas aliquid, distinctio soluta corporis quo expedita sapiente laboriosam. Ad deleniti ![Alternate text](/assets/img/posts/blog_img1.jpg \"Optional title\") maxime asperiores architecto ipsum itaque nisi hic, impedit obcaecati vel, iste quae necessitatibus nobis culpa doloremque sit.\n\n## Lorem ipsum dolor sit amet. \n\n1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, totam! \n2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati quod non rem earum temporibus, porro nostrum esse quibusdam nam animi. \n3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo recusandae quod animi alias, sint harum.\n\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet nostrum sequi odit consectetur nemo fuga cumque, rerum tenetur sit possimus.",
        likes: 1000,
        shares: 10,
        authorImg: "author1.jpg",
    },
    {
        id: 2,
        token: "aa2487addfadifakdnfad2874rjahdfkafki234wykafkadfadaf",
        title: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, eligendi.",
        handle: "Another-title-of-the-title",
        info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At ipsam non nihil voluptatibus velit nobis vitae odio esse laborum, sit atque soluta laboriosam cum deleniti quibusdam optio! Ullam a odit sint, incidunt ducimus, et. Aperiam repellendus nostrum exercitationem non, aliquam vitae fuga, recusandae cupiditate voluptate.",
        img: "blog_img2.jpg",
        authorId: "anandss",
        authorName: "Anand Singh",
        publishedDate: "2015-06-01",
        content: "Lorem ipsum dolor sit bold __amet__, consectetur adipisicing italic _elit_. Qui deleniti [link_name](http://www.domain.com \"Title of link\") recusandae, quas aliquid, distinctio soluta corporis quo expedita sapiente laboriosam. Ad deleniti ![Alternate text](/assets/img/posts/blog_img1.jpg \"Optional title\") maxime asperiores architecto ipsum itaque nisi hic, impedit obcaecati vel, iste quae necessitatibus nobis culpa doloremque sit.\n\n## Lorem ipsum dolor sit amet. \n\n1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, totam! \n2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati quod non rem earum temporibus, porro nostrum esse quibusdam nam animi. \n3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo recusandae quod animi alias, sint harum.\n\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet nostrum sequi odit consectetur nemo fuga cumque, rerum tenetur sit possimus.",
        likes: 100,
        shares: 10,
        authorImg: "author2.jpg",
    },
    {
        id: 3,
        token: "akfh29472398478dfjadfkafki234wykafkadfadaf",
        title: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
        handle: "This-is-one-the-title",
        info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti alias illo, exercitationem soluta qui et tenetur blanditiis! Sit earum, iusto totam, assumenda ex quam atque laborum vero inventore dicta in quasi vitae suscipit rerum, hic dignissimos, at quae deserunt aperiam.",
        img: "blog_img3.jpg",
        authorId: "sudkumar",
        authorName: "Sudhir Mitharwal",
        publishedDate: "2014-06-01",
        content: "Lorem ipsum dolor sit bold __amet__, consectetur adipisicing italic _elit_. Qui deleniti [link_name](http://www.domain.com \"Title of link\") recusandae, quas aliquid, distinctio soluta corporis quo expedita sapiente laboriosam. Ad deleniti ![Alternate text](/assets/img/posts/blog_img1.jpg \"Optional title\") maxime asperiores architecto ipsum itaque nisi hic, impedit obcaecati vel, iste quae necessitatibus nobis culpa doloremque sit.\n\n## Lorem ipsum dolor sit amet. \n\n1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, totam! \n2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati quod non rem earum temporibus, porro nostrum esse quibusdam nam animi. \n3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo recusandae quod animi alias, sint harum.\n\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet nostrum sequi odit consectetur nemo fuga cumque, rerum tenetur sit possimus.",
        likes: 1000,
        shares: 10,
        authorImg: "author1.jpg",
    },
    {
        id: 4,
        token: "kafda223askfhadfadkhawfpadhdfkafki234wykafkadfadaf",
        title: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem neque fuga dicta asperiores provident, obcaecati.",
        handle: "Mama-blog-is-here",
        info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor praesentium, cumque voluptatum maiores officiis ipsam quibusdam, aut illum earum, nam hic, cum nulla incidunt quisquam. Facere, aliquam a. Ad necessitatibus, in ducimus consectetur quas culpa. Culpa nemo, earum nesciunt iusto, placeat aliquid qui necessitatibus eius similique eos ipsa optio minima.",
        img: "blog_img4.jpg",
        authorId: "anandss",
        authorName: "Anand Singh",
        publishedDate: "2015-05-10",
        content: "Lorem ipsum dolor sit bold __amet__, consectetur adipisicing italic _elit_. Qui deleniti [link_name](http://www.domain.com \"Title of link\") recusandae, quas aliquid, distinctio soluta corporis quo expedita sapiente laboriosam. Ad deleniti ![Alternate text](/assets/img/posts/blog_img1.jpg \"Optional title\") maxime asperiores architecto ipsum itaque nisi hic, impedit obcaecati vel, iste quae necessitatibus nobis culpa doloremque sit.\n\n## Lorem ipsum dolor sit amet. \n\n1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, totam! \n2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati quod non rem earum temporibus, porro nostrum esse quibusdam nam animi. \n3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo recusandae quod animi alias, sint harum.\n\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet nostrum sequi odit consectetur nemo fuga cumque, rerum tenetur sit possimus.",
        likes: 100,
        shares: 10,
        authorImg: "author2.jpg",
    },
];